SELECT
    ROW_NUMBER () OVER (ORDER BY COUNT(LH.SONG_URL) DESC) ROWNUM,
    INFO.G_ARTIST,
    INFO.G_TITLE,
    COUNT(LH.SONG_URL)

FROM
    LISTEN_HISTORY LH
        INNER JOIN MUSIC_INFO_GOOGLE_ONLY INFO ON
            LH.SONG_URL = INFO.SONG_URL

WHERE 
    LH.LISTEN_DATE BETWEEN '2023-04-01' AND '2023-06-30'
    AND INFO.G_ARTIST <> 'ILLENIUM'
GROUP BY 
    INFO.G_ARTIST,
    INFO.G_TITLE

ORDER BY COUNT(LH.SONG_URL) DESC